version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.13.0
workflows:
  staging:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: ion-web
          extra-build-args: --build-arg TOKEN=${STAGING_TOKEN}
          filters:
            branches:
              only: main
